config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: %i[index show] do
    resources :groups, only: %i[ new create  show ] do 
      resources :categories, only: %i[ new create ]
    end
  end

  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorygroups, dependent: :destroy
  has_many :groups, through: :categorygroups

  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true
end

app/models/category_group.rb
class CategoryGroup < ApplicationRecord
  belongs_to :category
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :categorygroups, dependent: :destroy
  has_many :categories, through: :categorygroups, dependent: :destroy

  # Validation of inputs
  validates :icon, presence: true
  validates :name, presence: true

  def self.total_spending(group_id)
    sum = 0
    category_groups = CategoryGroup.all
    category_groups.each do |cat_group|
      next unless cat_group.group_id == group_id.to_i

      categories = Category.where(id: cat_group.category_id)
      categories.each do |category|
        sum += category.amount.to_i
      end
    end
    sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  #  Validation of input
  validates :name, presence: true
  validates :email, presence: true

  has_many :categories, dependent: :destroy
  has_many :groups, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    user_path(current_user) # your path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.all
  end

  def create
    @category = Category.new(
      name: allowed_params[:name],
      amount: allowed_params[:amount],
      user_id: current_user.id
    )

    if @category.save
      save_cat_group(@category)
      redirect_to user_group_path(current_user.id, params[:group_id]), notice: 'Successfully created Category spending'
    else
      render 'new', alert: 'Category group failed to create'
    end
  end

  private

  def save_cat_group(category)
    @category_group = CategoryGroup.create!(
      category_id: category.id,
      group_id: params[:group_id]
    )
  end

  def allowed_params
    params.require(:category).permit(:name, :amount)
  end
end

app/controllers/category_groups_controller.rb
class CategoryGroupsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    # Group id
    @groups = Group.where(user_id: current_user.id)
    @category_groups = CategoryGroup.all.order(created_at: :desc)
    p @groups
  end

  def new
    @groups = Group.all
  end

  def create
    @group = Group.new(
      user_id: allowed_params[:user_id],
      name: allowed_params[:name],
      icon: allowed_params[:icon]
    )

    if @group.save
      redirect_to user_path(current_user.id), notice: 'Group created successfully'
    else
      render 'new', alert: 'Group was not created'
    end
  end

  private

  def allowed_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    @user = User.find(params[:id])
    @groups = Group.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/entity_groups_helper.rb
module EntityGroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<%= render 'helper/nav_login_signup'%>

<div class = 'conatinaer'>
    <div class = 'container w-70'>
    <%= form_with model: @category, url: user_group_categories_path, scope: :category  do |form| %>
      <%= form.label 'Spending name', class: 'fs-5 mb-2 mt-4' %>
      <%= form.text_field :name, autofocus: true, autocomplete: "name", class:'form-control', require: true%>
      
       <%= form.label :amount, class: 'fs-5 mb-2 mt-4' %>
       <%= form.text_field :amount, autofocus: true, autocomplete: "amount", class:'form-control mb-4', require: true%>


      <div class="actions col-4 mx-auto mb-3">
        <%= form.submit "Add Spending", class: 'btn cat-color text-light mt-3' %>
      </div>

    <%end%>
</div>

app/views/category_groups/show.html.erb
<h2> Select trans </h2>

app/views/groups/new.html.erb
<%= render 'helper/nav_login_signup' %>

<div class = 'container py-4'>
  <h2 class = 'text-center'> Category </h2>

  <div class = 'container w-70'>
    <%= form_with model: @group, url: user_groups_path, scope: :group  do |form| %>

      <%= form.label 'Select a Category', class: 'fs-5 mb-2' %>
      <%= form.select :icon, options_for_select([
        ['Entertainment','party.png'],
        ['Cloth','cloth.png'],
        ['Education','education.png'],
        ['Food', 'food.png'],
        ['Hospital','hospital.png'],
        ['House','house.png'],
        ['Insurance', 'insurance.png'],
        ['Sport','sports.png'],
        ['Transportation','transportation.png']
        ]) , {}, class:'form-select mb-4', id: 'icon', aria_label: "form-select category" %>
         <%= form.hidden_field :user_id, value: current_user.id %>
        <div>
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>
        <div class = 'text-center'>
          <%= form.submit 'Add category', class: 'btn cat-color text-light mt-3' %>
        <div>
    <%end%>
  </div>
</div>

app/views/groups/show.html.erb
<nav class="navbar navbar-dark main-bg ">
  <div class="container">
      <%= link_to '←', user_path(current_user.id) , class:'text-light text-decoration-none fs-2' %>
      <a class="navbar-brand" href="#">Spending</a>
      <%= link_to 'Next',{}, class: 'text-light fs-5 text-decoration-none'%>
  </div>
</nav>
<div class = 'container pt-4 '>
  <% @groups.each do |group| %> 
    <% if group.id == params[:id].to_i %>
      <div class = 'd-flex flex-row justify-content-between w-70'>
          <div> <%= image_tag group.icon, class:'img' %> </div>
          <p> <strong><%= group.name %></strong> total spending: <strong>$<%= Group.total_spending(params[:id]) %> </strong></p>
      <%end%> 
    <%end%>
  </div>
   <div class = 'container py-3'>
      <% @category_groups.each do |cat_group| %>
        <% if cat_group.group_id == params[:id].to_i%>
          <% categories = Category.where(id: cat_group.category_id)%>
          <% categories.each do |category|%>
            <div class = 'card border-white'>
              <div class = 'card-body d-flex flex-row justify-content-between'>
                <div class = 'd-flex flex-column'>
                <p> <strong><%= category.name %></strong></p>
                <p>Date: &nbsp; <%= ((category.created_at).to_s)[0, 10] %> </p>
                </div>
                <p> <strong>$<%= category.amount %></strong></p>
              </div>
            </div>
          <%end%>
        <%end%>
      <%end%>
    </div>
  <div class = 'container cat-color py-3'>
    <div class = 'card cat-color border-white'>
      <div class = 'card-body text-center'>
        <%= link_to 'Add new Spending',new_user_group_category_path(current_user.id, params[:id]), class:'text-light text-decoration-none fs-4'%>
      </div>
    </div>
  </div>
</div>

app/views/helper/_nav_login_signup.html.erb
<nav class="navbar navbar-dark main-bg ">
  <div class="container">
   <%- if controller_name == 'confirmations' %>
      <%= link_to '←', root_path , class:'text-light text-decoration-none fs-2' %>
      <a class="navbar-brand" href="#">Resend confirmation info</a>
      <%= link_to 'Next',{}, class: 'text-light fs-5 text-decoration-none'%>
    <%end%>
   
    <%- if controller_name == 'passwords' %>
      <%= link_to '←', root_path , class:'text-light text-decoration-none fs-2' %>
      <a class="navbar-brand" href="#">Forgot password</a>
      <%= link_to 'Next',{}, class: 'text-light fs-5 text-decoration-none'%>
    <%end%>
       

    <%- if controller_name == 'registrations' %>
      <%= link_to '←', root_path , class:'text-light text-decoration-none fs-2' %>
      <a class="navbar-brand" href="#">Register</a>
      <%= link_to 'Next',{}, class: 'text-light fs-5 text-decoration-none'%>
    <%end%>

    <%- if controller_name == 'categories' %>
      <%= link_to '←', user_path(current_user.id) , class:'text-light text-decoration-none fs-2' %>
      <a class="navbar-brand" href="#">New category Spending</a>
      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search text-light" viewBox="0 0 16 16">
      <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </svg>
    <%end%>

    <%- if controller_name == 'sessions' %>
       <%= link_to '←', root_path, class:'text-light text-decoration-none fs-2' %>
       <a class="navbar-brand" href="#">Login</a>
       <%= link_to 'Login',{}, class: 'text-light fs-5 text-decoration-none'%>
    <%end%>

      <%- if controller_name == 'groups' %>
      <%= link_to '←', user_path(current_user.id), class:'text-light text-decoration-none fs-2' %>
       <a class="navbar-brand" href="#">Categories</a>
       <%= link_to 'Next',{}, class: 'text-light fs-5 text-decoration-none'%>
    <%end%>
  </div>
</nav>

app/views/helper/_navbar_transaction.html.erb
<nav class="navbar navbar-dark main-bg">
  <div class="container-fluid">
    <span class="navbar-toggler-icon"></span>
    <a class="navbar-brand" href="#">Categories</a>
    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search text-light" viewBox="0 0 16 16">
    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
  </div>
</nav>

app/views/helper/_notice.html.erb
<% if notice %>
   <p class="notice"><%= notice %></p>
<%end%>

<% if alert %>
   <p class="alert"><%= alert %></p>
<%end%>

app/views/homes/index.html.erb
<div class = 'ht container pt-4 d-flex flex-column  align-items-center justify-contents-center' >
  <%= render 'helper/notice'%>
  <h1 class = ' header ' > Budget application </h1>

  <div>
    <%= link_to 'Log in', user_session_path , class: 'btn main-bg text-light mt-4' %>
    <%= link_to 'Sign up', new_user_registration_path , class: 'btn main-bg text-light mt-4' %>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%# Rials code  %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Budget application</title>
  </head>
  <body>
    <%= yield %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/show.html.erb
<%= render 'helper/navbar_transaction'%>
<%= render 'helper/notice'%>
<div class = 'bg-grey'>
  <div class="card w-100 mb-4">
    <div class = 'card-body d-flex flex-row align-items-center justify-content-between'>
      <p> <strong> Hellow <%= @user.name %>  </strong> </p>
      <div>
        <%= button_to 'Logout', destroy_user_session_path , method: :delete,  class: 'btn main-bg text-light' %>
      </div>
    </div>
  </div>

  <div class = 'container'>
    <% @groups.each do |group| %>
      <div class="card w-100 mb-3 d-flex flex-row align-items-center justify-content-between">
        <div class="card-body d-flex flex-row align-items-center justify-content-between">
            <%= image_tag group.icon, class:'img' %>
          <p class='tex'><%= link_to group.name, user_group_path(current_user.id, group.id) %></p>
          <p class="card-text text-bold h6"><strong>$<%= Group.total_spending(group.id) %></strong></p>
        </div>
      </div>
    <%end%>
  </div>

  <div class = 'container cat-color py-3'>
    <div class = 'card cat-color border-white'>
      <div class = 'card-body text-center'>
        <%= link_to 'Add Category', new_user_group_path(params[:id]), class:'text-light text-decoration-none fs-4'%>
      </div>
    </div>
  </div>
</div>